name: heterograph

channels:
   - conda-forge

dependencies:
   - python>=3.10 
   - pip
   - graph-tool=3.0=*_301 # compatibility with zen3
   - graphviz
   - python-graphviz
   - pandoc

   - pip:
      - -e .




